


spring:
  jooq:
    sql-dialect: Mysql

  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3320/qtdb
    username: root
    password: 1234
    driver-class-name: net.sf.log4jdbc.DriverSpy
    #    driver-class-name: oracle.jdbc.driver.OracleDriver
    #    type: org.apache.tomcat.jdbc.pool.DataSource
    hikari:
      maximum-pool-size: 10
      connection-timeout: 60000

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      #      hibernate:   #??? DB?????? ???? ????
      #        dialect: org.hibernate.dialect.MySQL57Dialect
      #        storage_engine: innodb
      format_sql: true
      default_batch_fetch_size: 1000
    show_sql: true
    format_sql: true
    use_sql_comments: true
    jackson:
      serialization:
        fail-on-empty-beans: false
    open-in-view: false
server:
  port: 9101
# https://www.jooq.org/javadoc/latest/org.jooq/org/jooq/SQLDialect.html